### ISSUE TITLE
Scarped Icon, Thumbnail do not show up in Steam

### ISSUE THREAD

**Issue by halsafar** [SteamGridDB/steam-rom-manager#104]
SRM 2.2.15, Windows 10

Using out of the box settings for RetroArch - Nestopia UE (Nes) I was able to quickly get my games showing up in Steam.  The only issue is that no icons or thumbnails show up for any game unless I am in Grid view.  If I am in List or Detailed view every single game uses the RetroArch icon.  In the SRM Preview window however every single game has one or more images.

I tried to look around and determine if this is a feature SRM currently supports.  So I am not sure if this is a bug or a feature request.

**Comment by FrogTheFrog** [comment]
It's a known Steam limitation. It is possible to set an icon separatelly, however the path to the icon must be absolute.

**Comment by kencinder** [comment]
The icons are also limited in size to the same small icon you currently see, non steam games cannot use the "mini-banners" that Steam games do. Making them rather pointless to even use, as they're tiny.

**Comment by navajojoe** [comment]
SRM can upload titles in steams app list, shouldn't there be a similar method to automatically attach images to the apps? I don't understand the purpose of including the box art or otherwise images to see in the preview section of SRM if it isn't linked to steam.

**Comment by kencinder** [comment]
Banners do not equal Icons

This is a Steam limitation, only small square icons are supported for Non Steam Apps.

The images you see in preview are only shown in Grid and Big Picture mode.

As @FrogTheFrog stated above, icons are only supported when provided locally using `Local Icons` under Advanced Options.

**Comment by kencinder** [comment]
Icons are a different resolution than grids, so without image resizing on SRM's part...no.
Grids have to be 460x215 or multiples of such as 920x430.
Icons however are standard icon size of 32x32 or multiples of, and only display very small to begin with.

Art resized for icons looks absolutely terrible anyway, I've tried it...you can't even make anything out, looks like a blob, and I'm viewing it on a 100" screen even.

Unless Steam decides to allow Non Steam games to utilize the "mini" grids you see on retail games, consider SRM's icon support as no different than setting an icon for a Windows shortcut, because that's all Steam gives you to work with.

**Comment by FrogTheFrog** [comment]
I'm closing this issue until Steam decides to support mini-grids.
