### ISSUE TITLE
[Enhancement]  Auto search icon

### ISSUE THREAD

**Issue by ghost** [SteamGridDB/steam-rom-manager#12]
I do not know if it's possible, but look for icons for Wii U and 3ds games directly in Nintendo Eshop servers.

**Comment by FrogTheFrog** [comment]
@PirhanaPlant Sorry, but there is no real Icon provider to get non-steam icons from. Even if Nintendo Eshop had correctly sized icons, that would limit automatic icon search to Nintendo games. Also, I believe those icons are copyrighted. Therefore, I won't work on this enhancement.

P.S. I talked with the owner of `SteamGridDB` and he promised to update list (which I checked and it's has splatoon now). For force update list in this app wait 12h since last list check or delete `%partition%:\Users\%user%\AppData\Roaming\steam-rom-manager\userData\fuzzyList.json`
