### ISSUE TITLE
Plz ad support with openemu also when I try to add namco classic collection vol. 1 and vol. 2 it shows up as this

### ISSUE THREAD

**Issue by RegDuy** [SteamGridDB/steam-rom-manager#142]
![Screen Shot 2019-07-01 at 12 01 08 PM](https://user-images.githubusercontent.com/51733982/60460196-f28c0200-9bf7-11e9-9f88-b5fbd1c3fcc1.png)

**Comment by kencinder** [comment]
1: OpenEmu support would be in the form of a preset, ANYTHING that can be passed command line arguments to load content, can be used with SRM. You can create your own.
We do not have any fluent Mac users that openly and actively contribute, so if you are able to provide working parameters for a parser for OpenEmu, I can add it...otherwise, I do not use MacOS and am unable to.

2: The images being returned incorrectly, are due to the fact there *are* no images for those games on steamgriddb.com.
Both of those titles are Namco ND-1 Arcade games, and are not called this on PSP. The PSP game is one game title `Namco Museum Battle Collection` unless it's the Japanese version, which is split into two but still uses that title(And JP names for games are not used on the image provider, where an English one exists)
