### ISSUE TITLE
Executing the emulators with set cpu affinity?

### ISSUE THREAD

**Issue by AzazaelX** [SteamGridDB/steam-rom-manager#202]
Aight, I'm quite a dunce at this so bear with me. So I was wondering if there's a way to permanently set the specific cores affinity (Like only cpu 0 and cpu 2) once you launch a rom game in a emulator from steam.  I tried following a post and creating a bat file like this "Start /affinity 5 pcsx2.exe" and set the executable section like this "D:\PS2\PCSX2 1.6.0\Core Module.bat". But then I realize that it only run the emulator and not the rom once I try to launch the games from steam Library. Is it not possible or am I being an idiot and missing something here?

**Comment by cbartondock** [comment]
This has nothing to do with SRM. Personally not sure whether it's possible in the way you want. You could import the bat files instead of the games themselves (**Executable field**: _C:\launcher.bat_) and pass the specific rom as an argument to the bat file (**Command Line Arguments**: _"${filepath}"_), and pass that argument along to the emulator within the bat file (I think something like _"Start /affinity 5 pcsx2.exe %0"_)
