### ISSUE TITLE
Default/global user configuration

### ISSUE THREAD

**Issue by FrogTheFrog** [SteamGridDB/steam-rom-manager#23]
A seperate user configuration should be made available and made "global". User configuration should have most (not all) of fields that are available in usual user configurations. User then would have to click a switch button near a field title to use value from global configuration.

**Comment by HEspoke** [comment]
@FrogTheFrog created this issue in response to a long thread in #19 which was created by @ThePiranhaPlant . The issue was concerning creating a global settings option so that toggles can be made across parsers. These functions have since been added to the Settings section of SRM and added to each individual Parser.
