### ISSUE TITLE
Possibility to change the icons

### ISSUE THREAD

**Issue by Joesome** [SteamGridDB/steam-rom-manager#28]
@FrogTheFrog: There was a possibility in Ice to not only edit the Images for the "Grid view" but also for the icons (instead of the standard emulator icon).  This would make especially the standard Desktop List view in steam a lot more appealing. Is it possible to integrate that in your program? Keep up the good work! :)

**Comment by FrogTheFrog** [comment]
@Joesome Desktop icons are not yet supported, they will be once I integrate #19. However, I'm currently stuck with `priority` enchantments. And by stuck I mean that I literally can't address other issues until they are implemented.

**Comment by Joesome** [comment]
Wasn't sure that #19 was the same issue. Thanks anyway for your quick response!

 PS: If you need help for the German or French translation I may be of help :)

**Comment by FrogTheFrog** [comment]
@Joesome Translators are always welcome! By the way, how does ICE get icons? Downloads from somewhere or do you have to set directory which has them? I'm planing on going the second route as I don't know where I could download them from.

**Comment by Joesome** [comment]
@FrogTheFrog: Ice got Icons locally with set  directory. I used it to get an Icon per Console (E.g. A better SNES Icon for the SNES Console Emulation instead of the Emulator Icon)

**Comment by HEspoke** [comment]
I'll check on this when I get home from vacation. It's a holiday in the states so I am currently away. I don't remember any time that ice pulled images specially for icons. In the config.txt it only pulled from your steam local images directory and consolegrid. @FrogTheFrog I don't think SRM can do this currently because the GUI is based on pulling images in for BPM display . I don't think this is something that will be added to SRM but I don't know for sure .


-Tyler

**Comment by Joesome** [comment]
@HEspoke: When I recall it correctly you were able to add "icon=X:\folder\icon.png" in the consoles.txt file. That way it was possible to customize the Icon for a specific console.

**Comment by HEspoke** [comment]
OK, finally back home after visiting Canada over the holiday. I reviewed this issue posted by @Joesome and there are some unique distinctions that @Joesome is making that does not make it the same issue as #19 . Let me explain, @Joesome is referring to icons to be changed only for the purpose of the emulator itself to have a different image instead of each individual game to have different icon images. This would be useful if you do not use BPM at all and you want the emulator category to have the console images for each individual console category. Example would be that my entire SNES category of games would have a picture of a North American SNES ICON that would display next to each one of my SNES Roms as I selected them in Standard Mode (NON-BPM). The standard of the ICON image is as follows: 
---Icons: These are standard icons, you’ll need either a .exe with an embedded icon (like the .exe of the app itself, if it has an icon you want) or the icon you want to use as a .PNG  or .TGA file that’s square (e.g. 256 x 256 pixels) like a regular icon file.---

@FrogTheFrog I see that the image in #19 does have a ICON line already there. If that line is to find the ICON for the Standard NON-BPM Game then #19 is the same issue. I just wanted to clarify what @Joesome was trying to convey coming from an ICE environment.

**Comment by Joesome** [comment]
@HESpoke: thanks for clarifying. Yes changing Icons per Console is what worked with ICE and I would like to see it here too. I originally wanted to change the icon individually for every Game but I guess that is a bit too difficult to implement. 

For me it's just a big plus to see Console Icons instead of the Retroarch icon for every single Game when not in BP-Mode. Kind regards!
