### ISSUE TITLE
Change layout to grid

### ISSUE THREAD

**Issue by FrogTheFrog** [SteamGridDB/steam-rom-manager#30]
Somehow I missed the new css display style - grid. Changing layout to use grid would significantly simplify SRM and would make it easier to add new content.

If you are interested on how it will help, take a look here:
[![CSS Grid Changes EVERYTHING - Amazing Presentation](https://img.youtube.com/vi/7kVeCqQCxlk/0.jpg)](https://youtu.be/7kVeCqQCxlk?t=5m36s "CSS Grid Changes EVERYTHING - Amazing Presentation")

**Comment by HEspoke** [comment]
Hey @FrogTheFrog 
I know this post of "Changing layout to use grid" was added to your 2.1.0 release milestone. Was this implemented? I was waiting for your 2.1.0 release to bring up this minor glitch when building a APP list and the way the grid behaves.
 
This first picture is an example of when the App list is first generated and SRM is at full screen btw. You can see that the grid images are 2 wide in one row.
![2017-08-09 00_59_48-steam rom manager](https://user-images.githubusercontent.com/26511314/29105841-c9a51e00-7c9e-11e7-96fc-fdc6547e12e9.png)

Then if I just move the slider past 30% and immedately bring it back down to 30% it shows the grid images 3 wide ( I prefer 3 wide in one row that's why I discovered this)
![2017-08-09 01_00_30-steam rom manager](https://user-images.githubusercontent.com/26511314/29105861-fc002dae-7c9e-11e7-9add-33b22560e261.png)

Thanks for taking a look

**Comment by FrogTheFrog** [comment]
This is unrelated to grid, it's a bug related to slider value. Open a separate issue, meanwhile I'll try to fix it.

**Comment by FrogTheFrog** [comment]
Oh well, too late...

**Comment by HEspoke** [comment]
Sorry, I wasn't at the computer to open the issue. Thanks for taking care of it, I already loaded 2.1.1 and now it shows three grid images per row when in full screen. Good fix.
