### ISSUE TITLE
Using Retrogaming.cloud to match games instead of SteamGridDB

### ISSUE THREAD

**Issue by KristopherPeck** [SteamGridDB/steam-rom-manager#32]
Would it be possible to use Retrogaming.cloud to match games instead of SteamGridDB? Currently you can't add any games to SteamGridDB without contacting the creator while Retro allows any user to create game entries which makes it easier especially if someone has roms that aren't as popular as others. Granted there isn't a ton of quality control yet over excess entries or misspelled entries.

**Comment by HEspoke** [comment]
What is steamgamesdb? I never heard of it .

-Tyler

**Comment by KristopherPeck** [comment]
Sorry. I meant SteamGridDB. It's what the rom manager uses to match game titles.

**Comment by HEspoke** [comment]
Have you registered for it? My registration was instantaneous and not admin approved because it's based on you having a steam account . 

-Tyler

**Comment by KristopherPeck** [comment]
Yes I have. Registration does not allow you add a game to the database as I said above. If you go to add a grid image to a game that doesn't exist in the database you get an error saying it can't be added since it's doesn't exist. 
![capture](https://user-images.githubusercontent.com/21282789/28758092-bbc420ce-755f-11e7-8e1a-a1ad066ba14a.PNG)

**Comment by HEspoke** [comment]
I see what you mean. The creator does this deliberately in order to keep the database in order. I prefer that he does this and think that steamgriddb is one of the best out there. It is a very well maintained.
Please reply with a list of the games that need to be added to the database and I will verify them and add them to the database.

-Tyler

**Comment by FrogTheFrog** [comment]
@KristopherPeck I agree with @HEspoke. Database should be strictly maintained, otherwise there will be a lot of duplicates due to spelling mistakes or typos. For example, you also made a mistake :D . The correct title is "Hakuoki: Demon of the Fleeting Blossom". With multiple duplicate titles may split uploaded images that actually belong to one title, thus making it harder to retrieve them all. Therefore "SteamGridDB" will remain as a database that I will pull titles from. 

P.S. The owner of "SteamGridDB" also follows this repo, so if you find missing titles, just post them here.

**Comment by doZennn** [comment]
Hey, @KristopherPeck!
Only some select people have the ability to add games. @HEspoke being one of them.
Like the others have said, this is to keep it as clean as possible. 
I've added the Hakuoki games to the database.
