### ISSUE TITLE
[Enhancement] About screen

### ISSUE THREAD

**Issue by DannyMeister** [SteamGridDB/steam-rom-manager#48]
I don't see any place in the UI where I can see what version I have.  I'm sure I could look at the binaries directly, but in the UI is much nicer.  There's a few other helpful things that could be there as well.

- App version and build number/date
- Github link to download newer versions
- Links to help/FAQ
- Any other relevant links
- A little self-pimping for the developer
- Easter egg... you know you want to!

**Comment by HEspoke** [comment]
I suggested the build version add to the dev. It should already be listed at the top when you run the test parser and view your Log. 
 As for the Github Download page, @FrogTheFrog  put a link in the parser page to the Steam Group and from there it links to the latest stable build. I like the idea of the program linking users to something other then the github first, github can be intimidating to new users so if we can funnel them to the Steam Group page for download,discord, and updates I like that idea. Besides, if they have are running the program, they dont really need a download page since they are already running SRM. They need support usually. 
As for the other stuff.....ill defer to @frogthefrog =)

**Comment by DannyMeister** [comment]
Yep, the build version definitely belongs in the log as well.

**Comment by HEspoke** [comment]
If you run the test parser, it is listed at the top of the log.
