### ISSUE TITLE
Easy way to identify ROM from the app list

### ISSUE THREAD

**Issue by DannyMeister** [SteamGridDB/steam-rom-manager#49]
When an image/title was so far badly matched as to leave you unsure of what ROM it was trying to match, there isn't a quick easy way to identify which ROM you are having the issue with.  You can leave that screen and go to the Event Log to try to identify it.  Because the ROM path is on the command line shown under the title, then you can hover over the command line and wait about 10-15 seconds for it to scroll to the right far enough to see the name of the file.  It'd be much nicer if we could simply get the filename of the ROM shown somewhere on that tile, or perhaps better yet, a hover or right-click display of all the info as would show in the Event Log for that ROM.

**Comment by HEspoke** [comment]
Maybe @FrogTheFrog can add another search field at the top right corner. One for the Fuzzy matched results and one for the ROM filename. (he will probably hate this idea btw haha)

**Comment by FrogTheFrog** [comment]
I'll be doing a rewrite of preview window in order to try and increase rendering performance while images are being downloaded. I would also like to reduce app data being displayed to minimum (a separate window will contain a lot if not all of data about selected app). However, I'm bad at composition and stuff and I could use some help.

So, if anyone could provide me a doodle of how they think app container should be composed, I would be very thankful. For example:

![untitled](https://user-images.githubusercontent.com/22381748/29893001-4b7d4f24-8dd9-11e7-9ec2-2f63ee713074.png)

**Comment by kencinder** [comment]
What about using just a mouse-over tooltip window to display pertinent information, such as this? Simple and keep the preview window itself uncluttered.

**Comment by kencinder** [comment]
The above merged PR appears to work great when hovering over FinalTitle in the Preview window, think this issue can be closed.
